### ISSUE TITLE
Full Dataset Link

### ISSUE THREAD

**Issue by XiongZhongxia** [zhang-pengyu/DUT-VTUAV#1]
Thanks for your work! Can you provide us a link of the full dataset for downloading? Thanks again.

**Comment by zhang-pengyu** [comment]
Thanks for your attention. The dataset is available at https://zhang-pengyu.github.io/DUT-VTUAV/

**Comment by XiongZhongxia** [comment]
> Thanks for your attention. The dataset is available at https://zhang-pengyu.github.io/DUT-VTUAV/

Actually I asked for full dataset link because the provided links are for data splits... Could you please provide a single link to download the entire dataset? It'll be much more convenient.

**Comment by zhang-pengyu** [comment]
Sorry, we cannot provide a full dataset link because of file size limitation. For convenience, we will provide a bash/python file for downloading the full dataset automatically. Thanks for your advice.

**Comment by XiongZhongxia** [comment]
> Sorry, we cannot provide a full dataset link because of file size limitation. For convenience, we will provide a bash/python file for downloading the full dataset automatically. Thanks for your advice.

OK, thanks for your contribution.

**Comment by easycodesniper-afk** [comment]
> Sorry, we cannot provide a full dataset link because of file size limitation. For convenience, we will provide a bash/python file for downloading the full dataset automatically. Thanks for your advice.

I hope it could save your time.

LinkUrl：https://pan.baidu.com/s/1nUCkJ5volQhcCTrjjQZexA 
Password：2rb9

**Comment by XiongZhongxia** [comment]
> 

That's what I'm hoping for. Thanks a lot!

**Comment by XiongZhongxia** [comment]
> > Sorry, we cannot provide a full dataset link because of file size limitation. For convenience, we will provide a bash/python file for downloading the full dataset automatically. Thanks for your advice.
> 
> I hope it could save your time.
> 
> LinkUrl：https://pan.baidu.com/s/1nUCkJ5volQhcCTrjjQZexA Password：2rb9

That's what I'm hoping for. Thanks a lot!

**Comment by Yore0** [comment]
> > Sorry, we cannot provide a full dataset link because of file size limitation. For convenience, we will provide a bash/python file for downloading the full dataset automatically. Thanks for your advice.
> 
> I hope it could save your time.
> 
> LinkUrl：https://pan.baidu.com/s/1nUCkJ5volQhcCTrjjQZexA Password：2rb9

Thanks!!!
