### ISSUE TITLE
标注问题

### ISSUE THREAD

**Issue by easycodesniper-afk** [zhang-pengyu/DUT-VTUAV#2]
师兄你好！我在使用数据集时发现label的长度与序列中图片数对不上，请问VTUAV是每隔10帧标注一次吗？

**Comment by zhang-pengyu** [comment]
对的

**Comment by LACHENNG** [comment]
请问一下，为什么有的sequence长度和序列图片数却是一样的呢？比如序列‘pedestrian_085’, 此外，还有的序列好像并不是严格每10帧标注一次，比如pedestrian_057中图片3674张，txt文件里面有404行。这些问题导致无法确定标注的bbox和对应的图片关系。

**Comment by zhang-pengyu** [comment]
第一句没理解是什么意思（pedestrian_085共945张图片，95个标注），pedestrian_057我这边显示有4039张图片，404行标注

**Comment by LY-1** [comment]
您好，我刚看了一下相机（禅思H20T）的参数，它拍摄的分辨率是640*512，和论文中的640*480好像有出入？然后rescale到1920*1080具体是用的啥方法？

**Comment by zhang-pengyu** [comment]
@LY-1 抱歉，这个地方是我写错了，原图片大小是640*512，原图使用PIL库的resize函数（nearest neighbour插值）进行resize，配准，裁剪，得到最终RGB-T图像对

**Comment by LY-1** [comment]
方便告知配准和裁剪部分是咋做的吗？

**Comment by zhang-pengyu** [comment]
配准是通过手动在两张图上标出特征点对，计算仿射变换矩阵，将一张图warp到另一张图的坐标系下，实现配准，最后将两张图的共同区域裁剪下来，resize到同一分辨率（保证长宽比不变），如果需要可以share给你一份我用的代码

**Comment by LY-1** [comment]
十分感谢您！！！我想借鉴一下您的做法。方便的话可以通过邮箱发送给我。1053504537@qq.com。

**Comment by LACHENNG** [comment]
> 第一句没理解是什么意思（pedestrian_085共945张图片，95个标注），pedestrian_057我这边显示有4039张图片，404行标注

真相了，是我下载的压缩包里面几个出现了问题，导致丢失了数据 /捂脸

**Comment by LACHENNG** [comment]
> 配准是通过手动在两张图上标出特征点对，计算仿射变换矩阵，将一张图warp到另一张图的坐标系下，实现配准，最后将两张图的共同区域裁剪下来，resize到同一分辨率（保证长宽比不变），如果需要可以share给你一份我用的代码

你好，能否也提供一份代码，借鉴一下你的做法，谢谢了! transplus@foxmail.com

**Comment by HUOUO7** [comment]
> 配准是通过手动在两张图上标出特征点对，计算仿射变换矩阵，将一张图warp到另一张图的坐标系下，实现配准，最后将两张图的共同区域裁剪下来，resize到同一分辨率（保证长宽比不变），如果需要可以share给你一份我用的代码

你好，最近也在想红外-可见光图像对齐的方法，可不可以借鉴一下你的做法，十分感谢！[2576723077@qq.com](mailto:2576723077@qq.com)

**Comment by lyp19** [comment]
> 配准是通过手动在两张图上标出特征点对，计算仿射变换矩阵，将一张图warp到另一张图的坐标系下，实现配准，最后将两张图的共同区域裁剪下来，resize到同一分辨率（保证长宽比不变），如果需要可以share给你一份我用的代码

你好，最近也在想红外-可见光图像对齐的方法，可不可以借鉴一下你的做法，十分感谢！1761708364@qq.com

**Comment by zhang-pengyu** [comment]
抱歉回复晚了，我上传到网盘（链接: https://pan.baidu.com/s/10uHcGThutMmaI2SpcZKC8Q?pwd=98bf 提取码: 98bf）了，可以自取一下

**Comment by LACHENNG** [comment]
> 抱歉回复晚了，我上传到网盘（链接: https://pan.baidu.com/s/10uHcGThutMmaI2SpcZKC8Q?pwd=98bf 提取码: 98bf）了，可以自取一下

你好，链接失效能否重新发一份

**Comment by jeremisty99** [comment]
> 抱歉回复晚了，我上传到网盘（链接: https://pan.baidu.com/s/10uHcGThutMmaI2SpcZKC8Q?pwd=98bf 提取码: 98bf）了，可以自取一下

你好，链接失效能否重新发一份 非常感谢
