### ISSUE TITLE
annotation when using test set

### ISSUE THREAD

**Issue by LZ-QWQ** [zhang-pengyu/DUT-VTUAV#3]
I notice that your work uses test set to validate some trackers, but you also emphasize this benchmark provides only sparse annotation. So a problem is that did you validate trackers in sparse annotation or use a SOTA tracker to get dense annotation and then do evaluation like TrackingNet?
Thank you.

**Comment by zhang-pengyu** [comment]
We provide the evaluation results on our test set [here](https://github.com/zhang-pengyu/DUT-VTUAV#evaluation-toolkit--attribute-annotation). We do not provide dense annotation in the current version.
