### ISSUE TITLE
dense bounding box annotations

### ISSUE THREAD

**Issue by 972821054** [zhang-pengyu/DUT-VTUAV#4]
Hello, I want to ask you how you generate dense bounding box annotations? Thank you!

**Comment by zhang-pengyu** [comment]
We did not provide dense annotation in the current work. You can follow the description of TrackingNet[1] to produce dense annotations.

[1] TrackingNet: A Large-Scale Dataset and Benchmark for Object Tracking in the Wild. In ECCV 2018.

**Comment by 972821054** [comment]
@zhang-pengyu Have you tried generating dense annotations?

**Comment by zhang-pengyu** [comment]
No, but we plan to provide dense annotation in the extended work. If you have any detailed problem, you can list it under this issue

**Comment by 972821054** [comment]
@zhang-pengyu Hello, dense descriptions can be generated by the method in trackingnet. I can get better results with matlab version DCF, but there are still a few frames with poor results. The method of choosing sota may get better results. Since I don't currently use large datasets, dense boxes for all datasets are not generated. I'll close the question, thanks again for your contribution in this area!

**Comment by 972821054** [comment]
@zhang-pengyu Hello, dense descriptions can be generated by the method in trackingnet. I can get good results with matlab version DCF, but there are still a few frames with poor results. The method of choosing sota may get better results. Since I don't currently use large datasets, dense boxes for all datasets are not generated. I'll close the question, thanks again for your contribution in this area!
