### ISSUE TITLE
annotation问题

### ISSUE THREAD

**Issue by Moore-K2** [zhang-pengyu/DUT-VTUAV#5]
您好，我是对您这个数据集感兴趣的小白之一，请问标签文件四个坐标的具体含义是什么？

**Comment by Wangbiao2** [comment]
边界框左上角点的x,y坐标，以及框的宽高

**Comment by neuhsm** [comment]
我也是刚开始接触跟踪方向，根据这个数据集标注来看，这个是不是单目标跟踪的数据集啊，有没有多目标跟踪的无人机拍摄RGB-T数据集可以使用，目前找了好久数据集都没找到合适的
