### ISSUE TITLE
关于数据采样的问题

### ISSUE THREAD

**Issue by Haodong-Lei-Ray** [zhang-pengyu/DUT-VTUAV#6]
您好作者，我看到您的数据采样是使用大疆禅思系列H20T,我想问问有没有什么设备比较便宜的却又能做到红外图像与可见光图像的同时采集。发现一些海康微视红外的手持设备只能做到记录一种图像。

**Comment by zhang-pengyu** [comment]
现在热红外相机价格都偏高，而且市场上暂时没发现双目RGB-T相机
